# Generated by Django 2.0.3 on 2018-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'restUsers',
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
    ]
